### ISSUE TITLE
How to actually run these locally?

### ISSUE THREAD

**Issue by sureshvv** [bstavroulakis/web-components#1]
Can these be run using polymer serve?

That seems to be the recommended way these days.

Can you give me some pointers on how I can run them locally?

**Comment by bstavroulakis** [comment]
These are static files, so you can run them with any local server method you desire.
You can use the python SimpleHTTPServer, the node express module (https://expressjs.com/en/starter/static-files.html) or any other module (http://stackoverflow.com/questions/6084360/using-node-js-as-a-simple-web-server) and with polyserve as well.

**Comment by sureshvv** [comment]
I tried with python SimpleHTTPServer.

I had to change index.html as follows to prevent the 404 errors.

```
-  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
-  <link rel="import" href="../iron-component-page/iron-component-page.html">
+  <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
+  <link rel="import" href="bower_components/iron-component-page/iron-component-page.html">
```

I still get documentation not found and am unable to see the demo working,

Thanks for any piointers.

**Comment by sureshvv** [comment]
With the above changes, I have been able to run it with polymer serve. 

Thank you for your help.
